apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These components are installed by default because they're commonly used all
# software components deployed to the test infra cluster.
resources:
  - ../components/flux
  - ../components/cert-manager
  - ../components/kyverno
  - ../components/envoy-gateway-operator
  - ../components/telepresence
