apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Using installer manifests from Flux v2.3.0
  - github.com/fluxcd/flux2/manifests/install?ref=v2.7.5

patches:
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    path: kustomize-controller-patch.yaml
